SchoolOfCode/final-project-app-3-flamingos

package-lock.json
package.json
src/index.js
src/pages/Home.js

components should be individual components, these will be used to build pages/views in the pages folder

setup react routing and pages folder.

---

README.md

- added user personas and stories/journeys to readme

added user stories to readme

---

README.md
src/components/LoginForm/LoginForm.module.css
src/components/LoginForm/LoginForm.stories.js
src/components/LoginForm/index.js
src/components/RegisterForm/RegisterForm.module.css
src/components/RegisterForm/RegisterForm.stories.js
src/components/RegisterForm/index.js
src/index.js
src/pages/Login.js
src/pages/Register.js
src/pages/pages.stories.js

- added LoginForm component
- added RegisterForm component
- added stories for both
- added Login page
- added Register page
- added stories for both
_todo: css for both components_

Login Register

---

src/components/LoginForm/index.js
src/components/PostForm/index.js

this takes displayName from the JWT so we can attach a userId to the db save

added auth to post routes,

---

src/components/AddComment/index.js
src/components/LoginForm/index.js
src/components/PostForm/index.js
src/components/RegisterForm/index.js

- removed some middleware (I added this to try and get image upload working)
- put in some logic to check if there is an image

image uploads

---

package-lock.json
src/components/LoginForm/index.js

post route now secured with authentication

added authenticate logic to login using Route

---

package-lock.json
package.json
src/components/LoginForm/index.js
src/index.js
src/pages/Home/Home.module.css
src/pages/Home/index.js
src/pages/Login/index.js

added Links from Home to login and register

add login and register links from Home

---

src/components/RegisterForm/index.js
src/config/index.js
src/pages/Register/index.js

Added link to login after Register

add Link to login page after Register

---

package-lock.json
src/components/RegisterForm/index.js
src/index.js
src/pages/New/index.js

-checks user exists and changes button to Sign In
-Sign In redirects to Login page
-Also secured post route from unauthorised users

User exists

---

src/components/MobileMenu/index.js
src/components/Nav/index.js
src/pages/Login/index.js

-applied LoggedInContext to Nav
-added Link to mobile view
-added logic to hide Nav Menu except "Live" if user is not logged in

apply useContext to Nav and Link to mobile View nav bar

---

src/components/MobileMenu/index.js

-applied LoggedInContext to MobileView

Use context

---

package-lock.json
src/pages/Live/Live.module.css
src/pages/Live/index.js

-reversed live feed from latest
-added scrollbar to live feed container

Navigation

---

package-lock.json
package.json
src/components/PostForm/index.js

its not needed and caused errors

removed cloudinary npm pkg

---

src/pages/Live/Live.module.css

wanted box-shadow and -webkit-box-shadow

css had errors on live.module.css

---

src/components/SinglePost/index.js
src/pages/Live/index.js

Added time as this was missing in earlier branches/pull request

Added formatted time

---

src/components/RegisterForm/index.js
src/config/index.js

-After new user registers, page changes to login page for user to login

Registration check

---

src/components/PostForm/PostForm.module.css
src/components/PostForm/index.js
src/index.js
src/pages/Confirm/index.js

- isSending shows on submitting post
- once posted, redirects to confirm with no postId (its just a thank you message)
- once confirmed,  redirects to live page

Is sending

---

src/components/PostForm/index.js
src/components/ShowPost/index.js
src/pages/New/index.js

new post page now redirects to post page and shows the post is not confirmed yet

new post page now redirects.

---

package-lock.json
package.json
src/components/SinglePost/SinglePost.module.css
src/components/SinglePost/SinglePost.test.js
src/components/SinglePost/index.js
src/setUpTests.js

Tests for SinglePost

---

src/pages/Live/index.js

Date wasn't rendering in proper format when user not logged in. Now fixed.

Date format issues

---

src/components/Button/Button.test.js

This button component seems to have been used in only one part of the codebase. I wonder if it's necessary?

unit tests for Button component

---

src/components/RegisterForm/RegisterForm.test.js
src/components/ShowPost/ShowPost.test.js
src/components/SinglePost/SinglePost.test.js

unit tests for this component still in progress

Register form test

---

package-lock.json
src/pages/Live/index.js

fixed constant refresh of live page

hopefully fixed live page

---

src/components/AddComment/AddComment.module.css
src/components/AddComment/index.js
src/components/Comments/Comments.module.css
src/components/Comments/Comments.stories.js
src/components/Comments/index.js
src/components/Location/Location.module.css
src/components/MobileHeader/mobileHeader.module.css
src/components/PostForm/PostForm.module.css
src/components/SinglePost/SinglePost.module.css
src/components/SinglePost/index.js
src/pages/Live/Live.module.css
src/pages/Live/index.js
src/pages/New/New.module.css
src/pages/New/index.js
src/pages/Post/Post.module.css
src/pages/Post/index.js

- changed CSS for live, post and new page to try and make theming more consistent
- re-arranged single post component
- added comments component

changed loads of CSS

---

src/components/PostForm/index.js
src/components/PostImage/PostImage.module.css
src/components/PostImage/PostImage.test.js
src/components/PostImage/index.js
src/components/SinglePost/SinglePost.module.css
src/config/index.js
src/pages/Post/Post.module.css
src/pages/Post/index.js

- added postimage component
- tweaked css of other components

added image tag back to individual post page
